// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XHLS_HMM_H
#define XHLS_HMM_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xhls_hmm_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XHls_hmm_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XHls_hmm;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XHls_hmm_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XHls_hmm_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XHls_hmm_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XHls_hmm_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XHls_hmm_Initialize(XHls_hmm *InstancePtr, u16 DeviceId);
XHls_hmm_Config* XHls_hmm_LookupConfig(u16 DeviceId);
int XHls_hmm_CfgInitialize(XHls_hmm *InstancePtr, XHls_hmm_Config *ConfigPtr);
#else
int XHls_hmm_Initialize(XHls_hmm *InstancePtr, const char* InstanceName);
int XHls_hmm_Release(XHls_hmm *InstancePtr);
#endif

void XHls_hmm_Start(XHls_hmm *InstancePtr);
u32 XHls_hmm_IsDone(XHls_hmm *InstancePtr);
u32 XHls_hmm_IsIdle(XHls_hmm *InstancePtr);
u32 XHls_hmm_IsReady(XHls_hmm *InstancePtr);
void XHls_hmm_EnableAutoRestart(XHls_hmm *InstancePtr);
void XHls_hmm_DisableAutoRestart(XHls_hmm *InstancePtr);


void XHls_hmm_InterruptGlobalEnable(XHls_hmm *InstancePtr);
void XHls_hmm_InterruptGlobalDisable(XHls_hmm *InstancePtr);
void XHls_hmm_InterruptEnable(XHls_hmm *InstancePtr, u32 Mask);
void XHls_hmm_InterruptDisable(XHls_hmm *InstancePtr, u32 Mask);
void XHls_hmm_InterruptClear(XHls_hmm *InstancePtr, u32 Mask);
u32 XHls_hmm_InterruptGetEnabled(XHls_hmm *InstancePtr);
u32 XHls_hmm_InterruptGetStatus(XHls_hmm *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
