# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/HLS_hmm.xdc

# IP: ip/HLS_hmm_ap_fadd_3_full_dsp_32/HLS_hmm_ap_fadd_3_full_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HLS_hmm_ap_fadd_3_full_dsp_32 || ORIG_REF_NAME==HLS_hmm_ap_fadd_3_full_dsp_32}]

# IP: ip/HLS_hmm_ap_fdiv_14_no_dsp_32/HLS_hmm_ap_fdiv_14_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HLS_hmm_ap_fdiv_14_no_dsp_32 || ORIG_REF_NAME==HLS_hmm_ap_fdiv_14_no_dsp_32}]

# IP: ip/HLS_hmm_ap_fmul_2_max_dsp_32/HLS_hmm_ap_fmul_2_max_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HLS_hmm_ap_fmul_2_max_dsp_32 || ORIG_REF_NAME==HLS_hmm_ap_fmul_2_max_dsp_32}]
