# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/project.cache/wt [current_project]
set_property parent.project_path C:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip c:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/project.srcs/sources_1/ip/HLS_hmm_ap_fadd_3_full_dsp_32/HLS_hmm_ap_fadd_3_full_dsp_32.xci
set_property is_locked true [get_files c:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/project.srcs/sources_1/ip/HLS_hmm_ap_fadd_3_full_dsp_32/HLS_hmm_ap_fadd_3_full_dsp_32.xci]

read_ip c:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/project.srcs/sources_1/ip/HLS_hmm_ap_fdiv_14_no_dsp_32/HLS_hmm_ap_fdiv_14_no_dsp_32.xci
set_property is_locked true [get_files c:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/project.srcs/sources_1/ip/HLS_hmm_ap_fdiv_14_no_dsp_32/HLS_hmm_ap_fdiv_14_no_dsp_32.xci]

read_ip c:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/project.srcs/sources_1/ip/HLS_hmm_ap_fmul_2_max_dsp_32/HLS_hmm_ap_fmul_2_max_dsp_32.xci
set_property is_locked true [get_files c:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/project.srcs/sources_1/ip/HLS_hmm_ap_fmul_2_max_dsp_32/HLS_hmm_ap_fmul_2_max_dsp_32.xci]

read_verilog -library xil_defaultlib {
  C:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/HLS_hmm_CONTROL_BUS_s_axi.v
  C:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/HLS_hmm_fadd_32ns_32ns_32_5_full_dsp.v
  C:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/HLS_hmm_fdiv_32ns_32ns_32_16.v
  C:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/HLS_hmm_fmul_32ns_32ns_32_4_max_dsp.v
  C:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/HLS_hmm_mux_3to1_sel2_32_1.v
  C:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/HLS_hmm_ou.v
  C:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/HLS_hmm.v
}
read_xdc C:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/HLS_hmm.xdc
set_property used_in_implementation false [get_files C:/Users/Hanyan/Desktop/board2/microzed_axis/solution1/impl/verilog/HLS_hmm.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top HLS_hmm -part xc7z020clg484-1 -no_iobuf -mode out_of_context
write_checkpoint -noxdef HLS_hmm.dcp
catch { report_utilization -file HLS_hmm_utilization_synth.rpt -pb HLS_hmm_utilization_synth.pb }
