// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xhls_hmm.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XHls_hmm_CfgInitialize(XHls_hmm *InstancePtr, XHls_hmm_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XHls_hmm_Start(XHls_hmm *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_hmm_ReadReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XHls_hmm_WriteReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XHls_hmm_IsDone(XHls_hmm *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_hmm_ReadReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XHls_hmm_IsIdle(XHls_hmm *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_hmm_ReadReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XHls_hmm_IsReady(XHls_hmm *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHls_hmm_ReadReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XHls_hmm_EnableAutoRestart(XHls_hmm *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_hmm_WriteReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XHls_hmm_DisableAutoRestart(XHls_hmm *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_hmm_WriteReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XHls_hmm_InterruptGlobalEnable(XHls_hmm *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_hmm_WriteReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_GIE, 1);
}

void XHls_hmm_InterruptGlobalDisable(XHls_hmm *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_hmm_WriteReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_GIE, 0);
}

void XHls_hmm_InterruptEnable(XHls_hmm *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XHls_hmm_ReadReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_IER);
    XHls_hmm_WriteReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XHls_hmm_InterruptDisable(XHls_hmm *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XHls_hmm_ReadReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_IER);
    XHls_hmm_WriteReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XHls_hmm_InterruptClear(XHls_hmm *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHls_hmm_WriteReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XHls_hmm_InterruptGetEnabled(XHls_hmm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHls_hmm_ReadReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_IER);
}

u32 XHls_hmm_InterruptGetStatus(XHls_hmm *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHls_hmm_ReadReg(InstancePtr->Control_bus_BaseAddress, XHLS_HMM_CONTROL_BUS_ADDR_ISR);
}

